### ISSUE TITLE
Fix non-linear history handling

### ISSUE THREAD

**Issue by rvolosatovs** [TheThingsIndustries/release-notes#3]
#### Summary

The utility fails to handle non-linear history, e.g.: 
![2019-07-26-18:16:40-screenshot](https://user-images.githubusercontent.com/12877905/61966118-29c0b980-afd2-11e9-9e65-9ee1b60b3bb1.png)

#### Steps to Reproduce

1. `go run github.com/TheThingsIndustries/release-notes -owner TheThingsNetwork -repo lorawan-stack -token $(cat token) -base v3.0.4 -head v3.1.0`

#### What do you see now?

Release notes for the whole repo (???)

#### What do you want to see instead?

Only the release notes `v3.0.4` -> `v3.1.0`

#### How do you propose to implement this?

Find the common parent commit between `base` and `head` and only use the commits between `head` and the parent(which may or may not be equal to `base`)
Probably also excluding the PRs merged in `base`

#### Can you do this yourself and submit a Pull Request?

yes

**Comment by johanstokking** [comment]
Please consider https://keepachangelog.com/en/1.0.0/
